export declare function and(a: boolean, b: boolean): boolean;
export declare function or(a: boolean, b: boolean): boolean;
export declare function not(a: boolean): boolean;
export declare function add(a: number, b: number): number;
export declare function sub(a: number, b: number): number;
export declare function neg(a: number): number;
export declare function mul(a: number, b: number): number;
export declare function div(a: number, b: number): number;
export declare function mod(a: number, b: number): number;
export declare function eq(a: number, b: number): boolean;
export declare function neq(a: number, b: number): boolean;
export declare function gt(a: number, b: number): boolean;
export declare function lt(a: number, b: number): boolean;
export declare function ge(a: number, b: number): boolean;
export declare function le(a: number, b: number): boolean;
export declare function if_then_else(a: boolean, b: any, c: any): any;
export declare function max(a: number, b: number): number;
export declare function min(a: number, b: number): number;
export declare function abs(a: number): number;
export declare function sqrt(a: number): number;
export declare function log(a: number): number;
